### ISSUE TITLE
Declare user agent in HTTP calls

### ISSUE THREAD

**Issue by petrbouchal** [skvrnami/hlidacr#2]
Thanks for putting this package together - this will save me reusing bits of my own hacked-together code for accessing this API.

As per https://cran.r-project.org/web/packages/httr/vignettes/api-packages.html, it would be good if the package sent a user agent string to the server as part of HTTP ({httr} calls) (the URL of this repo might be a good one).

Happy to submit a PR - though perhaps you are on it already: I was about so submit an issue/PR around the token on env vars and I see in NEWS that's already done...

**Comment by skvrnami** [comment]
Thanks for the comment and the link. I will fix it in a moment.
